name: Build and Deploy to Pages
on: [push]
env:
  SURVEY_FOODDATA_ZIP_URL: 'https://fdc.nal.usda.gov/fdc-datasets/FoodData_Central_survey_food_json_2021-10-28.zip'
  SURVEY_FOODDATA_ZIP_FILENAME: 'FoodData_Central_survey_food_json_2021-10-28.zip'
  SURVEY_FOODDATA_JSON_FILENAME: 'FoodData_Central_survey_food_json_2021-10-28.json'
  FOODDATA_DIR: fooddata
  VEGATTRIBUTES_ZIP_URL: 'https://github.com/v3gtb/fooddata-vegattributes/releases/download/v0.8.0/VegAttributes_for_FoodData_Central_survey_and_sr_legacy_food_json_2021-10-28-v0.8.0.zip'
  VEGATTRIBUTES_ZIP_FILENAME: 'VegAttributes_for_FoodData_Central_survey_and_sr_legacy_food_json_2021-10-28-v0.8.0.zip'
  VEGATTRIBUTES_JSON_FILENAME: 'VegAttributes_for_FoodData_Central_survey_and_sr_legacy_food_json_2021-10-28-v0.8.0.json'
permissions:
  contents: write
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install project's Python package
        run: pip install -e .
      - name: Load USDA FDC FoodData and VegAttributes data from cache
        id: download
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.FOODDATA_DIR }}
            indexed_FoodData_Central_survey_and_sr_legacy_food_json_2021-10-28.jsons.zip
          key: v4-${{ env.SURVEY_FOODDATA_ZIP_URL }}-${{ env.VEGATTRIBUTES_ZIP_URL }}
      - name: Download USDA FDC FoodData and VegAttributes data
        if: steps.download.outputs.cache-hit != 'true'
        run: >
          (
            mkdir -p "$FOODDATA_DIR" &&
            cd "$FOODDATA_DIR" &&
            if [ ! -f "$SURVEY_FOODDATA_ZIP_FILENAME" ]; then
              curl "$SURVEY_FOODDATA_ZIP_URL" -o "$SURVEY_FOODDATA_ZIP_FILENAME" &&
              unzip "$SURVEY_FOODDATA_ZIP_FILENAME";
            fi
            if [ ! -f "$VEGATTRIBUTES_ZIP_FILENAME" ]; then
              curl -L "$VEGATTRIBUTES_ZIP_URL" -o "$VEGATTRIBUTES_ZIP_FILENAME" &&
              unzip "$VEGATTRIBUTES_ZIP_FILENAME";
            fi
          )
      - name: Set up symlinks for input files
        run: |
          ln -s "$FOODDATA_DIR/$SURVEY_FOODDATA_JSON_FILENAME"
          ln -s "$FOODDATA_DIR/$VEGATTRIBUTES_JSON_FILENAME" "VegAttributes_for_FoodData_Central_survey_and_sr_legacy_food_json_2021-10-28.json"
      - name: Build
        run: |
          python prepare_data.py
          python plot.py
          mkdir -p build
          mv index.html plot.json build/
      - name: Deploy to GitHub pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
